version: "3"

services:
  app:
    container_name: zapaan_app
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - ./zapaan:/zapaan
      - public-data:/zapaan/public
      - tmp-data:/zapaan/tmp
      - log-data:/zapaan/log

    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production

  web:
    container_name: zapaan_web
    build: nginx
    volumes:
      - public-data:/zapaan/public
      - tmp-data:/zapaan/tmp
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
    public-data:
    tmp-data:
    log-data:
