version: "3"

services:
  # db:
  #   container_name: zapaan_db
  #   image: mysql
  #   command: mysqld --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_USER: root
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - '3316:3306'
  #   volumes:
  #     - ./db/mysql/volumes:/var/lib/mysql

  app:
    container_name: zapaan_app
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - ./zapaan:/zapaan
      - public-data:/zapaan/public
      - tmp-data:/zapaan/tmp
      - log-data:/zapaan/log
    depends_on:
      - db
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  web:
    container_name: zapaan_web
    build: nginx
    volumes:
      - public-data:/zapaan/public
      - tmp-data:/zapaan/tmp
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
    public-data:
    tmp-data:
    log-data:
