version: "3"

services:
  db:
    container_name: rails_db
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql

  app:
    container_name: rails_server
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./zapaan:/zapaan
    depends_on:
      - db
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  nginx:
    build:
      context: containers/nginx
    volumes:
      - ../volumes/app:/app                         # 静的ファイル
      - ../volumes/web/log:/var/log/nginx/          # Nginxのログ
      - ../volumes/ssl:/etc/nginx/cert/             # SSL証明書
    ports:
      - 80:80
    depends_on:
      - app
